updating ingress step

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -7,6 +7,11 @@ on:
       - "src/web-site/**"
       - "src/web-supervisor/**"
 
+env:
+  ALLOWED_PATHS: "src/web-admin src/web-site src/web-supervisor"
+  STAGING_HOST_PREFIX: "staging-pr"
+  STAGING_HOST_DOMAIN: "sample.com"
+
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -32,7 +37,7 @@ jobs:
         run: |
           git fetch origin
 
-          ALLOWED_PATHS=("src/web-admin" "src/web-site" "src/web-supervisor")
+          IFS=' ' read -ra ALLOWED_PATHS_ARR <<< "$ALLOWED_PATHS"
 
           BASE_REF=${{ github.event.pull_request.base.ref }}
           HEAD_SHA=${{ github.event.pull_request.head.sha }}
@@ -42,7 +47,7 @@ jobs:
             sort -u | \
             grep -v '^.$' | \
             while read -r dir; do
-              for allowed in "${ALLOWED_PATHS[@]}"; do
+              for allowed in "${ALLOWED_PATHS_ARR[@]}"; do
                 if [[ "$dir" == "$allowed" || "$dir" == "$allowed"/* ]]; then
                   echo "$dir"
                   break
@@ -58,18 +63,24 @@ jobs:
         run: |
           PR_NUMBER=${{ github.event.pull_request.number }}
           RANDOM_STRING=$(openssl rand -hex 3)  # Generates a short random string
-          STAGING_HOST="staging-pr-${PR_NUMBER}-${RANDOM_STRING}.ulak.com"
+          STAGING_HOST="${STAGING_HOST_PREFIX}-${PR_NUMBER}-${RANDOM_STRING}.${STAGING_HOST_DOMAIN}"
           echo "Generated staging URL: $STAGING_HOST"
           echo "staging_host=$STAGING_HOST" >> $GITHUB_ENV
 
       - name: Modify ingress.yml
         run: |
           for folder in $changed_dirs; do
-            if [[ -f "$folder/ingress.yml" ]]; then
-              echo "Updating ingress.yml in $folder"
-              yq e ".rules[].host = \"$staging_host\"" -i $folder/ingress.yml
+            url=$(grep "${folder}" README.md | grep -o 'https://[^)]*')
+            if [ -n "$url" ]; then
+              echo "URL found for ${folder} in README.md"
+              echo "URL: $url"
+              yq e ".rules[].host = \"$staging_host\"" -i .iac/ingress.yml
+            else
+              echo "${folder} url not found in README.md"
+              exit 1
             fi
           done
+          cat .iac/ingress.yml
 
       - name: Deploy to Kubernetes
         run: |
